### ISSUE TITLE
Cannot use multiple grids

### ISSUE THREAD

**Issue by knl** [BrianGilbert/mjolnir.bg.grid#8]
Not sure if possible, but I couldn't find a way to have multiple grids exist at the same time.

**Comment by BrianGilbert** [comment]
Can you explain what you mean?

**Comment by knl** [comment]
In my Slate setup I had settings that allowed me to make windows that are either one half, or a third, or a fourth of a screen width, and a full height. I could chose which one I need based on the different choice of key modifiers. In my understanding, that would mean having a 2x1, 3x1, or 4x1 grid in Mjolnir. However, the code assumes there will be only a single grid (at least, that's what I got from my limited understanding of lua modules).

What I would like to have is something like:

```
local grid22 = require "mjolnir.bg.grid"
local grid33 = require "mjolnir.bg.grid"
local grid42 = require "mjolnir.bg.grid"

grid22.setgrid(2,2)
grid33.setgrid(3,3)
grid42.setgrid(4,2)
```

**Comment by knl** [comment]
I was playing a bit with the module and mjolnir, and I got this in my `init.lua` script:

```
local grid22 = require "mjolnir.bg.grid"
local grid33 = require "mjolnir.bg.grid"

grid22.GRIDHEIGHT = 2
grid22.GRIDWIDTH = 2
grid33.GRIDHEIGHT = 3
grid33.GRIDWIDTH = 3

local cmdalt   = {"cmd", "alt"}

hotkey.bind(cmdalt, 'h', function()
  local win = window.focusedwindow()
  local f = {x = 0, y = 0, w = 1, h = grid22.GRIDHEIGHT}
  grid22.set(win, f, win:screen())
end)
```

Now, I would expect that `Cmd-Alt-h` would give me a window in the left hand side of the screen, half screen's width and full screen's height. Instead, I get a window that is one third of the screen wide.

**Comment by BrianGilbert** [comment]
So it sounds to me that mjomatic is what you need..  https://rocks.moonscript.org/modules/habbie/mjolnir.7bits.mjomatic

But if your wanting to align windows more granularly you can also set the grid count a lot higher.. I use 13 for instance.

**Comment by knl** [comment]
No, mjomatic isn't what I need, but thanks anyway. It is not just aligning them, but also making them of a specific width/height.

**Comment by BrianGilbert** [comment]
yes, so all you need to do is set higher count for GRIDWIDTH and GRIDHEIGHT

Here is what I'm using in Hammerspoon (a fork of Mjolnir)

```
grid.GRIDHEIGHT = 13
grid.GRIDWIDTH = 13

local mash = {"cmd", "alt", "ctrl"}
local mashshift = {"cmd", "alt", "ctrl", "shift"}

--move windows as per grid segments
hotkey.bind(mash, 'DOWN', grid.pushWindowDown)
hotkey.bind(mash, 'UP', grid.pushWindowUp)
hotkey.bind(mash, 'LEFT', grid.pushWindowLeft)
hotkey.bind(mash, 'RIGHT', grid.pushWindowRight)

--resize windows to grid
hotkey.bind(mashshift, 'UP', grid.resizeWindowShorter)
hotkey.bind(mashshift, 'DOWN', grid.resizeWindowTaller)
hotkey.bind(mashshift, 'RIGHT', grid.resizeWindowWider)
hotkey.bind(mashshift, 'LEFT', grid.resizeWindowThinner)
```
